[profile.default]
src = 'contracts'
out = 'out'
test = 'test/foundry'
libs = ['node_modules', 'lib']
script = 'script'
cache_path = 'cache-forge'
gas_reports = ["*"]

# solc_version = '0.8.14'

ffi = true

[fuzz]
runs = 500

[invariant]
runs = 500

[rpc_endpoints]
mainnet = "${ETH_NODE_URI_MAINNET}"
rinkeby = "${ETH_NODE_URI_RINKEBY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
rinkeby = { key = "${ETHERSCAN_API_KEY}" }